name: 全てのステップ (Update, Generate and Upload)

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update database
        run: curl -fsSL -X POST -H "Content-type:application/json" --data '{"user_id":"${{ secrets.ES_BASIC_ID }}", "passwd":"${{ secrets.ES_BASIC_PASS }}"}' ${{ secrets.UPDATE_ENDPOINT }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Create .env file
        run: |
          touch .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID}} > .env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET}} >> .env
        working-directory: /
      - name: Install dependencies
        run: npm i
      - name: Nuxt generate
        run: npm run generate
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          SOURCE_DIR: "togotv"
